version: "3.8"

services:
  db:
    image: "mysql:5.7.22"
    container_name: mysql_hotel
    ports:
      - "3366:3306"  
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: abc123
      MYSQL_DATABASE: db_hotel_bookings
      MYSQL_PASSWORD: abc123
      TZ: "Asia/Shanghai"
    volumes:
      - ./storage/mysql:/var/lib/mysql
    networks:
      - default

  rdb:
    image: redis:6.2-alpine
    container_name: redis_hotel
    restart: always
    ports:
      - "6399:6379"
    environment:
      - TZ=Asia/Shanghai
    command: redis-server /etc/redis/redis.conf --appendonly yes
    networks:
      - default
    volumes:
      - ./storage/redis:/data
      - ./storage/redis/redis.conf:/etc/redis/redis.conf

      
networks:
  default: