// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0
// source: booking_status.sql

package db

import (
	"context"
)

const ListBookingStatus = `-- name: ListBookingStatus :many
SELECT id, status_type, status_label FROM booking_status ORDER BY id
`

func (q *Queries) ListBookingStatus(ctx context.Context) ([]*BookingStatus, error) {
	rows, err := q.db.QueryContext(ctx, ListBookingStatus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*BookingStatus{}
	for rows.Next() {
		var i BookingStatus
		if err := rows.Scan(&i.ID, &i.StatusType, &i.StatusLabel); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
