// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package db

import (
	"time"
)

// 预订表
type Booking struct {
	// 主键
	ID uint32 `json:"id"`
	// 外键,用户表ID
	UserID uint32 `json:"user_id"`
	// 入住日期
	BookingFrom time.Time `json:"booking_from"`
	// 退房日期
	BookingTo time.Time `json:"booking_to"`
	// 外键,客房表ID
	RoomID uint32 `json:"room_id"`
	// 入住人数
	Members uint32 `json:"members"`
	// 总金额(单位分)
	TotalAmount uint32 `json:"total_amount"`
	// 创建时间
	CreatedAt time.Time `json:"created_at"`
	// 更新时间
	UpdatedAt time.Time `json:"updated_at"`
}

// 预定类型表
type BookingStatus struct {
	// 主键
	ID uint32 `json:"id"`
	// 客房类型
	StatusType string `json:"status_type"`
	// 客房类型标签
	StatusLabel string `json:"status_label"`
}

// 酒店表
type Hotel struct {
	// 主键
	ID uint32 `json:"id"`
	// 酒店名称
	Title string `json:"title"`
	// 酒店编码
	Code string `json:"code"`
	// 酒店地址
	Address string `json:"address"`
	// 创建时间
	CreatedAt time.Time `json:"created_at"`
	// 更新时间
	UpdatedAt time.Time `json:"updated_at"`
	// 是否删除, 0:正常, 1:删除
	IsDeleted bool `json:"is_deleted"`
}

// 付款表
type Payment struct {
	// 主键
	ID uint32 `json:"id"`
	// 外键,预定表ID
	BookingID uint32 `json:"booking_id"`
	// 支付类型(-1:取消支付,0:未支付,1:现金,2:微信,3:支付宝,4:银联,5:其他)
	PaymentType int32 `json:"payment_type"`
	// 付款金额(单位分)
	PaymentAmount uint32 `json:"payment_amount"`
	// 是否删除, 0:正常, 1:删除
	IsDeleted bool `json:"is_deleted"`
}

// 客房表
type Room struct {
	// 主键
	ID uint32 `json:"id"`
	// 外键,酒店表ID
	HotelID uint32 `json:"hotel_id"`
	// 客房号
	RoomNumber string `json:"room_number"`
	// 客房图片
	RoomImage string `json:"room_image"`
	// 客房价格(单位分)
	RoomPrice uint32 `json:"room_price"`
	// 外键,预定类型表ID
	BookingStatusID uint32 `json:"booking_status_id"`
	// 外键,客房类型表ID
	RoomTypeID uint32 `json:"room_type_id"`
	// 容纳人数
	RoomCapacity uint32 `json:"room_capacity"`
	// 客房描述
	RoomDescription string `json:"room_description"`
	// 创建时间
	CreatedAt time.Time `json:"created_at"`
	// 更新时间
	UpdatedAt time.Time `json:"updated_at"`
	// 是否删除, 0:正常, 1:删除
	IsDeleted bool `json:"is_deleted"`
}

// 客房类型表
type RoomType struct {
	// 主键
	ID uint32 `json:"id"`
	// 客房类型
	RoomType string `json:"room_type"`
	// 客房类型标签
	RoomLabel string `json:"room_label"`
}

// 会话表
type Session struct {
	// 主键
	ID uint32 `json:"id"`
	// Token的唯一标识uuid
	TokenID string `json:"token_id"`
	// 外键,用户表ID
	UserID uint32 `json:"user_id"`
	// 用户的refresh token
	RefreshToken string `json:"refresh_token"`
	// 登录设备的信息
	UserAgent string `json:"user_agent"`
	// 登录时IP
	ClientIp string `json:"client_ip"`
	// session或refresh token 过期时间
	ExpiresAt time.Time `json:"expires_at"`
	// 创建时间
	CreatedAt time.Time `json:"created_at"`
	// 登录类型(0:密码登录, 1:短信验证码)
	LoginType int32 `json:"login_type"`
}

// 用户表
type User struct {
	// 主键
	ID uint32 `json:"id"`
	// 用户手机号码
	PhoneNumber string `json:"phone_number"`
	// 哈希密码
	HashedPassword string `json:"hashed_password"`
	// 用户名称
	Username string `json:"username"`
	// 用户头像
	Avatar string `json:"avatar"`
	// 创建时间
	CreatedAt time.Time `json:"created_at"`
	// 更新时间
	UpdatedAt time.Time `json:"updated_at"`
	// 是否删除, 0:正常, 1:删除
	IsDeleted bool `json:"is_deleted"`
}
