// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package db

import (
	"time"
)

// 预定类型表
type BookingStatus struct {
	// 主键
	ID uint32 `json:"id"`
	// 客房类型
	StatusType string `json:"status_type"`
	// 客房类型标签
	StatusLabel string `json:"status_label"`
}

// 酒店表
type Hotel struct {
	// 主键
	ID uint32 `json:"id"`
	// 酒店名称
	Title string `json:"title"`
	// 酒店编码
	Code string `json:"code"`
	// 酒店地址
	Address string `json:"address"`
	// 创建时间
	CreatedAt time.Time `json:"created_at"`
	// 更新时间
	UpdatedAt time.Time `json:"updated_at"`
	// 是否删除, 0:正常, 1:删除
	IsDeleted bool `json:"is_deleted"`
}

// 客房表
type Room struct {
	// 主键
	ID uint32 `json:"id"`
	// 外键,酒店表ID
	HotelID uint32 `json:"hotel_id"`
	// 客房号
	RoomNumber string `json:"room_number"`
	// 客房图片
	RoomImage string `json:"room_image"`
	// 客房价格(单位分)
	RoomPrice uint32 `json:"room_price"`
	// 外键,预定类型表ID
	BookingStatusID uint32 `json:"booking_status_id"`
	// 外键,客房类型表ID
	RoomTypeID uint32 `json:"room_type_id"`
	// 容纳人数
	RoomCapacity uint32 `json:"room_capacity"`
	// 客房描述
	RoomDescription string `json:"room_description"`
	// 创建时间
	CreatedAt time.Time `json:"created_at"`
	// 更新时间
	UpdatedAt time.Time `json:"updated_at"`
	// 是否删除, 0:正常, 1:删除
	IsDeleted bool `json:"is_deleted"`
}

// 客房类型表
type RoomType struct {
	// 主键
	ID uint32 `json:"id"`
	// 客房类型
	RoomType string `json:"room_type"`
	// 客房类型标签
	RoomLabel string `json:"room_label"`
}
