// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package sqlc

import (
	"context"
	"database/sql"
)

type Querier interface {
	DeleteHotelByID(ctx context.Context, id uint32) error
	DeleteRoomByID(ctx context.Context, id uint32) error
	GetHotelByID(ctx context.Context, id uint32) (*Hotel, error)
	GetHotels(ctx context.Context, arg GetHotelsParams) ([]*Hotel, error)
	GetHotelsByTitle(ctx context.Context, arg GetHotelsByTitleParams) ([]*Hotel, error)
	GetRoomByID(ctx context.Context, id uint32) (*Room, error)
	GetRooms(ctx context.Context, arg GetRoomsParams) ([]*Room, error)
	GetRoomsByHotelID(ctx context.Context, arg GetRoomsByHotelIDParams) ([]*Room, error)
	InsertHotel(ctx context.Context, arg InsertHotelParams) (sql.Result, error)
	InsertRoom(ctx context.Context, arg InsertRoomParams) (sql.Result, error)
	UpdateHotel(ctx context.Context, arg UpdateHotelParams) error
	UpdateRoom(ctx context.Context, arg UpdateRoomParams) error
	UpdateRoomBookingStatus(ctx context.Context, arg UpdateRoomBookingStatusParams) error
	UpdateRoomType(ctx context.Context, arg UpdateRoomTypeParams) error
}

var _ Querier = (*Queries)(nil)
