// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0
// source: room_types.sql

package db

import (
	"context"
)

const ListRoomTypes = `-- name: ListRoomTypes :many
SELECT id, room_type, room_label FROM room_types ORDER BY id
`

func (q *Queries) ListRoomTypes(ctx context.Context) ([]*RoomType, error) {
	rows, err := q.db.QueryContext(ctx, ListRoomTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*RoomType{}
	for rows.Next() {
		var i RoomType
		if err := rows.Scan(&i.ID, &i.RoomType, &i.RoomLabel); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
